### ISSUE TITLE
Can't reset window size (to restore aspect ratio)

### ISSUE THREAD

**Issue by Michaelangel007** [badvision/jace#27]
* [x] The main window can be resized which is awesome. :+1: 
* [x] One can also hold down the `Shift` key to maintain the aspect ratio. :+1: 

The problem is if the window is re-sized and the aspect ratio is lost, I don't see a way to reset the window dimensions back to their default values (to restore aspect ratio). :-(  User error or a bug?

**Comment by badvision** [comment]
Would it be acceptable to have some kind of keystoke to set the window size to 1x, 1.5x, 2x, etc?

**Comment by Michaelangel007** [comment]
Keys would be great !  All I need is:

* 1x
* 2x
* 4x (optional)

**Comment by badvision** [comment]
2x is already pretty darn big -- I did 1x, 1.5x and 2x.  Let me know if that's sufficient.

**Comment by Michaelangel007** [comment]
* :+1: hotkeys
* :+1: 2x is great!  

I think I can hack up a 4x mode to try on my retina MacBook Pro to test that out.

However, there is a bug with the aspect ratio -- I'm not sure if it with the default or the 1x one though?

 This is the default screen.
![jace_default_ar](https://cloud.githubusercontent.com/assets/7876796/13200230/cc0ba494-d7f3-11e5-84c9-739315f434d5.png)

And this is the AR 1x.
![jace_ar1](https://cloud.githubusercontent.com/assets/7876796/13200232/d916d0e6-d7f3-11e5-9cab-5685586d849b.png)

**Comment by Michaelangel007** [comment]
The hotkey is especially appreciated because it exits fullscreen mode!

`Ctrl-Command-F` doesn't exit fullscreen mode -- bug?

**Comment by badvision** [comment]
The default is supposed to be 560x384 when you launch which is the same as 1x aspect mode.  I've added a line to call the same method at start to ensure consistency.

To see if the aspect is correct, a really good test is to launch Apple Desktop 2 which starts with a checkerboard monochrome screen.  When the aspect ratio is even slightly off the Moire pattern makes it quite apparent.  Compare the two:

<img width="564" alt="screen shot 2016-02-20 at 8 30 34 pm" src="https://cloud.githubusercontent.com/assets/5144198/13200625/8be0acde-d816-11e5-9d58-eb4af7198034.png">
vs 
<img width="569" alt="screen shot 2016-02-20 at 8 31 30 pm" src="https://cloud.githubusercontent.com/assets/5144198/13200627/9137e3d2-d816-11e5-83c3-9fc72625f53d.png">

The same is true for vertical aspect but it's not as immediately obvious because it's already doubled to start with.

As for fullscreen, there are some left-overs from when Jace was swing-based that quite obviously do not work at all.  I hadn't looked into the fullscreen bit because the normal window controls "just work" for going full-screen on Mac OSX and so hotkey-based fullscreen wasn't a priority.  I'll take another look at it.

**Comment by badvision** [comment]
Let me know if you're happy with the outcome here and I'll close this -- otherwise let me know how you'd like this to proceed further if needed. @Michaelangel007

**Comment by Michaelangel007** [comment]
Sorry Blurry won't get a chance to test this until later this week as I'm away for a business trip.

I'm assuming one of these images on Asimov is the `Apple II Desktop` program?

* ./images/masters/other_os/gui/Apple II Desktop 1.1.po
* ./images/masters/other_os/gui/A2Desktop.po

**Comment by badvision** [comment]
I think both are correct -- at any rate you just need a b&w checkerboard.

**Comment by Michaelangel007** [comment]
The 1x aspect ratio is still wrong.  The inside frame is 1120x724, which should be 1120x**768**.

![apple_ntsc_colors](https://cloud.githubusercontent.com/assets/7876796/13307385/0c670060-db28-11e5-90c3-b99ef45a5b7f.png)

Can't verify if latest changes fix due to blocked by #28 :-/

**Comment by badvision** [comment]
I think it's setting the total window size, not accounting for the size of the title bar.  I'll see if there's a sane way to handle that.

**Comment by badvision** [comment]
@Michaelangel007 I think this fixes it -- let me know what you think! :smile:

**Comment by Michaelangel007** [comment]
Verified fix at 1920x1080 (scaled) and at 2880x1880 (native) !

**Comment by Michaelangel007** [comment]
I added 3x zoom for a retina 2880x1880 (native)

https://github.com/Michaelangel007/jace/commit/8833f80138e3a00dc3dc7fa52d9730727f394c42

**Comment by badvision** [comment]
That's awesome!  Can you send a pull request my way?

**Comment by badvision** [comment]
Thanks @Michaelangel007!  I've merged it back to the mainline.  In case you didn't see more recent commits, I'm trying to get rewind/state management working next.  That one is a beast. :frowning:

**Comment by Michaelangel007** [comment]
No prob -- you're welcome!  Sorry I haven't been following the rewind/state management -- too much stuff going on in Real-Life (TM) last week and this week. :-/
