### ISSUE TITLE
[OSX] Command-V to paste text into Jace is ignored and treated as `v`

### ISSUE THREAD

**Issue by Michaelangel007** [badvision/jace#6]
OSX uses the native `Command-V` to paste text.  Jace ignores it and generates a plain `v` instead.

**Comment by badvision** [comment]
That's because command and option are open/close apple and overlap the Apple+C shortcut that some apps might use.  However, there are ZERO apple programs that can detect the presence of SHIFT so most of the shortcuts in Jace actually use ctrl+shift as the modifier instead.

For example ctrl+shift+c opens configuration, crtl+shift+v pastes system clipboard to the emulator as keystrokes, and so on.  If you have the friendly help-screen active it tells you some of these on boot and others it hints that you can find by opening the configuration with ctrl+shift+c, and so on.
